# Generated by Django 5.0.4 on 2024-04-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnailImagePath',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=256),
        ),
    ]
