# Generated by Django 5.0.4 on 2024-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_thumbnailimagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnailImagePath',
            field=models.CharField(max_length=256),
        ),
    ]
