# Generated by Django 5.0.4 on 2024-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_thumbnailimagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnailImagePath',
            field=models.CharField(default='blank', max_length=256),
        ),
    ]
